server:
  port: 10001
  servlet:
    context-path: /aub
spring:
  application:
    name: service-user
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
knife4j:
  enable: true
