server:
  port: 10002
spring:
  application:
    name: service-order
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
knife4j:
  enable: true
